program_committee:
  - venue: "EDM"
    years: "2026"
  - venue: "IUI"
    years: "2026"

external_reviewing:
  - venue: "AMCIS"
    years: "2026"
  - venue: "CHI"
    years: "2025, 2026"
  - venue: "CHI Case Studies"
    years: "2024"
  - venue: "CHI Late-Breaking Work"
    years: "2025"
  - venue: "CHI PLAY"
    years: "2026"
  - venue: "CSCL"
    years: "2026"
  - venue: "CUI Short Papers & Works-in-Progress"
    years: "2026"
  - venue: "Creativity & Cognition"
    years: "2025"
  - venue: "Creativity & Cognition Pictorials"
    years: "2026"
  - venue: "DIS"
    years: "2024, 2026"
  - venue: "DIS Provocations & Works-in-Progress"
    years: "2026 (Special Recognition for Outstanding Review)"
  - venue: "ECIS"
    years: "2026"
  - venue: "IDC"
    years: "2026"
  - venue: "IDC Work-in-Progress"
    years: "2024"
  - venue: "IMX"
    years: "2025"
  - venue: "IUI"
    years: "2025"
  - venue: "OzCHI Late-Breaking Works"
    years: "2025"
  - venue: "TEI Work in Progress"
    years: "2025"
  - venue: "UIST"
    years: "2026"

poster_jury:
  - venue: "CHI"
    years: "2026"
  - venue: "Creativity & Cognition"
    years: "2026"

volunteering:
  - "Student Volunteer, ACM CSCW 2024 & ACM ISS 2024"
  - "Vice Chair, Winter Seminar Series (WSS) 2023, Sharif University"
  - "Vice Chair, DataDays 2022, Sharif University"
  - "Head of Scientific Team, Webelopers 2022 & 2023, Sharif University"
  - "Head of Scientific Team, League of Coders 2022, Sharif University"
  - "Head of Branding Team, HardWar 2023, Sharif University"
  - "Head of Technical & Branding Team, HardWar 2022, Sharif University"
  - "Head of Human Resources Team, WSS 2022, Sharif University"
  - "Central Council Member, Students Scientific Chapter (SSC), Sharif University (2022-2023)"
