reviewing:
  - "ACM CHI 2025"
  - "ACM IUI 2025"
  - "ACM DIS 2024 (WiP)"
  - "ACM CHI 2024 (Case Study)"
  - "ACL BEA Workshop (Sub-reviewer)"

volunteering:
  - "Student Volunteer, ACM CSCW 2024 & ACM ISS 2024"
  - "Vice Chair, Winter Seminar Series (WSS) 2023, Sharif University"
  - "Vice Chair, DataDays 2022, Sharif University"
  - "Head of Scientific Team, Webelopers 2022 & 2023, Sharif University"
  - "Head of Scientific Team, League of Coders 2022, Sharif University"
  - "Head of Branding Team, HardWar 2023, Sharif University"
  - "Head of Technical & Branding Team, HardWar 2022, Sharif University"
  - "Head of Human Resources Team, WSS 2022, Sharif University"
  - "Central Council Member, Students Scientific Chapter (SSC), Sharif University (2022-2023)"
